[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "core",
    "email-validator>=2.3.0",
    "fastapi>=0.142.2",
    "pwdlib[argon2]>=0.3.1",
    "sqlalchemy>=2.1.1",
    "utils",
    "uvicorn>=0.54.0",
]

[build-system]
requires = ["uv_build>=0.8.18,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
core = { workspace = true }
utils = { workspace = true }
